---
- name: Prepare existing DC
  hosts:
    - existingdc
  roles:
    - role: trippsc2.create_testing_ad_domain

- name: Prepare new DC
  hosts:
    - dc
  gather_facts: false
  roles:
    - role: trippsc2.join_testing_ad_domain
      vars:
        dc_inventory_name: existingdc

- name: Prepare Vault server
  hosts:
    - vault
  pre_tasks:
    - name: Bootstrap python for Ansible
      become: true
      ansible.builtin.raw: |
        command -v python3 python || (
        command -v apk >/dev/null && sudo apk add --no-progress --update python3 ||
        (test -e /usr/bin/dnf && sudo dnf install -y python3) ||
        (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal)) ||
        (test -e /usr/bin/yum && sudo yum -y -qq install python3) ||
        (test -e /usr/sbin/pkg && sudo env ASSUME_ALWAYS_YES=yes pkg update && sudo env ASSUME_ALWAYS_YES=yes pkg install python3) ||
        (test -e /usr/sbin/pkg_add && sudo /usr/sbin/pkg_add -U -I -x python%3.7) ||
        echo "Warning: Python not bootstrapped due to unknown platform."
        )
      changed_when: false
  roles:
    - role: trippsc2.create_testing_hashicorp_vault
  tasks:
    - name: Create secret engine
      delegate_to: localhost
      trippsc2.hashi_vault.vault_kv2_secret_engine:
        token: "{{ vault_token }}"
        url: "{{ vault_url }}"
        engine_mount_point: os
        state: present
